### ISSUE TITLE
Could you provide the implementations of baselines?

### ISSUE THREAD

**Issue by Jxu-Thu** [yxuansu/SimCTG#1]
Thanks for your great work!

I would like to re-train the model with different training methods for comparison such as MLE training, unlikelihood training vs contrastive training.

Could you provide the implementation of MLE, unlikelihood training to reproduce the experimental results in the paper?

**Comment by yxuansu** [comment]
> Thanks for your great work!
> 
> I would like to re-train the model with different training methods for comparison such as MLE training, unlikelihood training vs contrastive training.
> 
> Could you provide the implementation of MLE, unlikelihood training to reproduce the experimental results in the paper?

Hi,

Thank you for your interest in our work. For the MLE baseline, you can just set the margin as 0 in the training scripts like here (https://github.com/yxuansu/SimCTG/blob/d79716f3a0e2e80623fc733fdca1508c4c8581bf/document_generation/train.sh#L6). We discuss the reason in section 3.1 of the paper.

For the Unlikelihood baseline, we used the official code here (https://github.com/facebookresearch/unlikelihood_training). Please refer to more details from the official implementation.

Feel free to ask me if you have more question :-)
