### ISSUE TITLE
请问contrastive loss对生成的影响程度如何，应如何定义contrastive loss和生成的cross-entropy loss的权重大小？

### ISSUE THREAD

**Issue by yuanhuachao** [yxuansu/SimCTG#10]
contrastive loss值范围在[0,1)，而生成的cross-entropy loss可能比较大，请问这种情况如何定义两个loss的各自权重比较好？小数据上试验了下，第一个batch的contrastive loss为0.09x，cross-entropy loss为9.x，后者为前者的100倍左右。
还有contrastive loss的margin，依据什么来定义，如何定义比较好？

**Comment by yxuansu** [comment]
Hi @yuanhuachao,

一般来说，两个loss的权重设置为一样即可。对于语言模型的训练来说，我们更关注的或者说更重要的loss term是cross-entropy loss。contrastive loss起的作用是辅助调节表示空间的分部，所以其magnitude不需要太大。

对于margin的选择，根据我们在Wikitext-103上的实验来看(i.e., Figure 3)，取0.5比较好。如果在新的数据集上进行实验的话，推荐先用0.5试一试。之后可以再根据实验结果进行调整。

**Comment by yuanhuachao** [comment]
理解了，十分感谢！
