### ISSUE TITLE
Dialogue generation training with simctg library

### ISSUE THREAD

**Issue by lecrycry** [yxuansu/SimCTG#11]
Hello,

Very good job for your work. It's amazing !

I want to train the dialogue generation with the library simctg. But the dataclass changes between the original source code and the example of "training_tutorial_on_wikitext103".

I'm using GTP2 and I want to reproduce DailyDialog results. Did I need to get the original dataclass for dialogue generation ? Or the new dataclass in "training_tutorial_on_wikitext103" works for all examples and English and Chinese GPT2 ? Specially for the tokens ?

Did I need to change something to the "training_tutorial_on_wikitext103" example for english dialogue generation ?

Thanks for help.

**Comment by yxuansu** [comment]
Hi @lecrycry,

Thank you for your interest in our work.

You can directly use the codes provided in "training_tutorial_on_wikitext103" to reproduce the results on dialogue generation. The only thing you need to take care of is making sure your file format is consistent with our wikitext-103 files provided in the training example.
