### ISSUE TITLE
fast_contrastive_search只支持batch_size=1吗

### ISSUE THREAD

**Issue by awdrgyjilplij** [yxuansu/SimCTG#12]
我只有batch_size=1能跑起来
这是为啥呢
或者有什么办法改进一下吗
感谢

**Comment by yxuansu** [comment]
Hi @awdrgyjilplij,

目前我们的实现只支持batch size = 1。我们的code在这里面可以找到(https://github.com/yxuansu/SimCTG/tree/main/simctg)。欢迎你pull request来帮助我们实现batch功能。
