### ISSUE TITLE
Bloom Ai

### ISSUE THREAD

**Issue by lecrycry** [yxuansu/SimCTG#17]
Hello,

Good job and congrats for NEURIPS 2022 !

Do you plan to support Bloom AI from BigScience ? If not, could you give me some clues to do it ?

Thanks for your come back.

**Comment by yxuansu** [comment]
Hi @lecrycry -- Thank you for your interest in work!

I wonder does huggingface support Bloom AI models? Because contrastive search has been integrated to huggingface `transformers` and will be released in their new release of next month. Do you think it will be helpful?

**Comment by lecrycry** [comment]
Yes Huggingface supports Bloom AI so I think it will work correctly with the next release.

Last question, do you know if their new release will integrate Contrastive search training as well ? Or only for the inference ?

Thanks a lot.

**Comment by yxuansu** [comment]
Hi @lecrycry -- They will first integrate the contrastive search only. The contrastive training might be integrated in the future.
