### ISSUE TITLE
Have you tested the effect of Contrastive Search method on encoder+decoder model such as BART?

### ISSUE THREAD

**Issue by maojinyang** [yxuansu/SimCTG#2]

**Comment by maojinyang** [comment]
I want to apply the Contrastive Search method on a BART model.  I modified the  code, but I got very bad results. I'm not sure if this is because of my code implementation or the model structure. Thank you in advance for your answer.

**Comment by yxuansu** [comment]
> I want to apply the Contrastive Search method on a BART model. I modified the code, but I got very bad results. I'm not sure if this is because of my code implementation or the model structure. Thank you in advance for your answer.

Hi, thank you for your interest in our work. Actually, I tried contrastive search on encoder-decoder model before and it works reasonably well. Could you drop me an email (ys484@cam.ac.uk) then I can share you the code?

**Comment by maojinyang** [comment]
Email:mjyang@ir.hit.edu.cn
Thank you so much！

**Comment by maojinyang** [comment]
Thank you so much!

**Comment by Atharva-Phatak** [comment]
@yxuansu Can you please add guidelines how we can adopt this code for BART models ?

**Comment by yxuansu** [comment]
> @yxuansu Can you please add guidelines how we can adopt this code for BART models ?

@Atharva-Phatak Hi, you can check here (https://github.com/yxuansu/SimCTG#12-simctg-elsewhere). They provide a really good implementation of how to adapt it on T5 model.

**Comment by yxuansu** [comment]
@Atharva-Phatak @maojinyang 
Hi, 
Just for your information, we have provided instructions of how to apply contrastive search on encoder-decoder models in the repo. Please find more details here (https://github.com/yxuansu/SimCTG/tree/main/SimCTGEncDec).
