### ISSUE TITLE
SimCTGT5和fast_contrastive_search相关问题（EncDecContrastiveDecodingOneStepFast）

### ISSUE THREAD

**Issue by Xyr990127** [yxuansu/SimCTG#20]
您好，请问SimCTGT5在做fast_contrastive_search时为什么batch size只能设置为1才可运行？

**Comment by yxuansu** [comment]
Hi @Xyr990127 -- 同学你好。我们原始的代码实现确实只是支持batch size=1。不过现在Huggingface已经将contrastive search集成到`transformers`中，HF中contrastive search是支持batch inference的。(1) 关于参数的设置可以参考这个[文档](https://huggingface.co/docs/transformers/main_classes/text_generation#transformers.generation_utils.GenerationMixin.generate.penalty_alpha)。(2) 对于方法调用的例子可以参考[这里](https://huggingface.co/blog/introducing-csearch#52-generating-text-with-contrastive-search)。不同的生成模型对generate函数的调用都是一样的。

注意一下，在使用之前要安装最新版的`transformers`。
```yaml
pip install torch
pip install "transformers>=4.24.0"
```

**Comment by Xyr990127** [comment]
> 

好的，我试试看，谢谢！
