### ISSUE TITLE
Contrastive Training loss的部分疑惑

### ISSUE THREAD

**Issue by aa327chenge** [yxuansu/SimCTG#21]
Contrastive Training过程中
CL-loss中有一部分为  = 常量 - s(hxi, hxi) + s(hxi, hxi)
s(hxi, hxi)  当s为cos时候  中间s(hxi, hxi) 是否恒为1？

**Comment by yxuansu** [comment]
@aa327chenge -- 这个部分对的。我们在论文第三页的footnote 2中也做了说明。
