### ISSUE TITLE
Questions about Document Generation

### ISSUE THREAD

**Issue by dongqian0206** [yxuansu/SimCTG#22]
Hi there,

Thanks for releasing the codes. Much appreciated.

I have two questions regarding the document generation task, i.e., Table 1 in your paper.

1.  Which size of pre-trained GPT-2 did you use to compute MAUVE? In the original MAUVE paper, they tried different sizes.
2. It seems to me that the length of the generated output matters when we try to alleviate the repetition problem, i.e., shorter, less repetitive. Could you recall the average length of the generated outputs?

Thank you in advance and looking forward to hearing from you.

Best,

Dong

**Comment by minji-o-j** [comment]
https://github.com/yxuansu/SimCTG/issues/7

I think they use the smallest version of GPT-2 (https://huggingface.co/gpt2)
