### ISSUE TITLE
similar sentence generation

### ISSUE THREAD

**Issue by nikky4D** [yxuansu/SimCTG#8]
Can this be modified to generate similar sentences given an input sentence?

**Comment by yxuansu** [comment]
Hi @nikky4D,

Can you provide more details of your task formulation? For example, which is the input and output of the language model?

**Comment by nikky4D** [comment]
The input to the language model is my own sentence. The expected output of the language model is a sentence. The output sentence will have similar meaning to the input sentence, but may be phrased differently. 

Eg: input -- The cat is yellow ->  gives output -> That cat over there is yellow. Sentence is similar in meaning and important nouns that were being referred to in the input sentence are preserved.
