### ISSUE TITLE
关于fast_contrastive_search实现中新生成的token的embedding的理解(hv)

### ISSUE THREAD

**Issue by HUSTHY** [yxuansu/SimCTG#9]
代码和论文的公式大体上看明白了，这里有一个点不是很理解，期待你们的回答。
下一个token的top_k_ids采用的是当前轮gpt的logits[:, -1, :]取tok得到的；而计算hv(也就是这个token的embedding)的时候为却采用top_k_ids和当前轮的past_key_values过模型得到新的hidden_states，并把hidden_states[-1]作为前面提到的那个token的embedding。
这里就得这样理解——生成的那个token当前轮是虚的，当前轮得到的hidden_states就是所有的输入的embedding，而这个新生成的token如何得到embedding就必须旧的input+生成的token过模型得到新的hidden_states，最后一个embedding就是之前的那个token的embedding；而新的一轮生成的token仍然只有index，没有embedding

这样的理解没有问题吧？

**Comment by gmftbyGMFTBY** [comment]
没问题

**Comment by HUSTHY** [comment]
已收到！谢谢！                          ——黄洋

**Comment by HUSTHY** [comment]
> 没问题

对了还有一个问题，你在知乎上说这个解码算法是一个确定性的算法，不能很好的产生多样性，你们在实际使用的时候采用的是先使用sample等解码算法解码一部分token，然后使用contrastive search decoding算法来补齐，得到了最好的效果；

那可不可以直接在ranking_fast那个计算步骤中，最后不仅仅取最大的那个，取前两个、前三个Id这种，稍微损失一些性能的前提下提升多样性；在性能和多样性上做一个平衡

不过这个思路没有验证过。。。

**Comment by yxuansu** [comment]
> > 没问题
> 
> 对了还有一个问题，你在知乎上说这个解码算法是一个确定性的算法，不能很好的产生多样性，你们在实际使用的时候采用的是先使用sample等解码算法解码一部分token，然后使用contrastive search decoding算法来补齐，得到了最好的效果；
> 
> 那可不可以直接在ranking_fast那个计算步骤中，最后不仅仅取最大的那个，取前两个、前三个Id这种，稍微损失一些性能的前提下提升多样性；在性能和多样性上做一个平衡
> 
> 不过这个思路没有验证过。。。

这个应该也可以。不过sampling几个token对性能的整体影响也不大。

**Comment by HUSTHY** [comment]
谢谢回复

**Comment by yxuansu** [comment]
> 谢谢回复

不客气。有问题的话咱们随时交流。
